### ISSUE TITLE
add FHIRConceptCodeMaps 

### ISSUE THREAD

**Issue by SevKohler** [SevKohler/FHIRconnect#11]
for term mappings

**Comment by SevKohler** [comment]
@gasperr we need to define the spec for that, so i could add it already to this version. 
Do we want to add this to the model mapping file in general ? 
Or how did you imagined that, i have no experience with conceptMaps. 
```YAML
  terminology:   # can be here within a specific mapping or even above in the header of the model.yml, in which case all CODEABLECONCEPT and CODING will try to be translated
    type: "local"         # local means that the embedded openFHIR terminology service will be used; alternatively, 'remote' is possible, see Integrations
    conceptmap: "http://url-of-the-conceptmap" # ConceptMap.url
```
