### ISSUE TITLE
condition needs to be redesigned

### ISSUE THREAD

**Issue by SevKohler** [SevKohler/FHIRconnect#12]
The current way condition is written is very confusing. 
Since the path has to be equal to the fathers path in order to let him know which one of a list to pick. 
```YAML
  - name: "deathDateTime"
    with:
      fhir: "$resource.deceased.as(DateTime)"
      openehr: "$resource/data[at0001]/items[at0024]"
    condition:
      targetRoot: "$resource"
      targetAttribute: "deceased"
      operator: "not empty"
```
I think thats very un intuitive, i would like just to write $fhirRoot which would take the deceaseDateTime and thats it. 
The attribute would be important if its a list, but maybe even then just target is enough ?!
