### ISSUE TITLE
We need a way to escape FHIR bad ID management

### ISSUE THREAD

**Issue by SevKohler** [SevKohler/FHIRconnect#17]
Otherwise:
```YAML
  - name: "request"
    with:
      fhir: "$resource.request"
      openehr: "$archetype/protocol[at0030]/items[at0103]"
      type: "NONE"
    followedBy:
      mappings:
        - name: "identifier"
          with:
            fhir: "$fhirRoot.as(Reference).identifier"
            openehr: "$openehrRoot"
          openehrCondition:
            targetRoot: "$openehrRoot"
            targetAttribute: "links"
            operator: "empty"

        - name: "identifierInReference"
          with:
            fhir: "$fhirRoot.as(MedicationRequest)"
            openehr: "$reference"
          openehrCondition:
            targetRoot: "$openehrRoot"
            targetAttribute: "links"
            operator: "not empty"
          reference:
            resourceType: "MedicationRequest"
            mappings:
              - name: "identifierInReference"
                with:
                  fhir: "$fhirRoot.identifier"
                  openehr: "$openehrRoot"
#              - name: "medicationRequestMapping"
#                with:
#                  fhir: "$fhirRoot"
#                  openehr: "$openehrRoot/links" # will use link
#                openehrLink:
#                  meaning: "the medication request for this medication"
#                  type: "medicationRequest"

```
