### ISSUE TITLE
open issue bakcwards mapping from openEHR into several resources

### ISSUE THREAD

**Issue by SevKohler** [SevKohler/FHIRconnect#5]
```
  - name: "category"
    with:
      fhir: "$resourcePath.category"
      openehr: "$archetypePath/data[at0001]/events[at0002]/data[at0003]/items[at0005]" # if there are several events add it to all of them
      # Backwards map all the values back, if they overlap ?!?!?!?

  - name: "conclusion"
    with:
      fhir: "$resourcePath.conclusion"
      openehr: "$archetypePath/data[at0001]/events[at0002]/data[at0003]/items[at0057]"
```

In this example we can have several events, if these events have different conlusions and categories, there should be different DiagnosticReports created. 
I need to introduce an something like a "unique" keyword (or leave this to custom code), that will create a new resource if the category mapping is provided twice by openEHR with two different value.
